name: Deploy

on:
  push:
    branches:
      - main

env:
  REGION_DEFAULT: us-east-1
  CLUSTER_NAME: EKS-fastfood

jobs:

 deploy:
    name: Deploying RDS 
    runs-on: ubuntu-latest    
    
    environment: #Define a configuração de ambiente para este job
      name: AWS       

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Terraform Init - RDS
        run: terraform init

      - name: Terraform Plan - RDS
        run: terraform plan -out=tfplan

      - name: Terraform Apply - RDS
        run: terraform apply -auto-approve tfplan
      
